name: Stormbreaker Snake Animation

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stormbreaker Snake
        uses: Platane/snk@master
        with:
          github_user_name: venkatesh520556
          outputs: |
            dist/stormbreaker-snake.svg?color_snake=00ccff&color_dots=#ff3300,#ffd700,#00ffff,#ffffff
            dist/stormbreaker-snake-dark.svg?palette=github-dark&color_snake=66ccff&color_dots=#ff6600,#00ffcc,#ffffff,#ffcc00
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
